### PR TITLE
style(clang-tidy): fix misc-use-anonymous-namespace

### LINKED ISSUE #1678: ClangTidy warnings for `misc-use-anonymous-namespace`
```
/Users/jviotti/Projects/core/src/core/jsonschema/frame.cc:15:13: error: function 'find_anchors' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   15 | static auto find_anchors(const sourcemeta::core::JSON &schema,
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/frame.cc:101:13: error: function 'find_nearest_bases' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
  101 | static auto find_nearest_bases(
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/frame.cc:230:13: error: function 'traverse_origin_instance_locations' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
  230 | static auto traverse_origin_instance_locations(
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/frame.cc:267:13: error: function 'repopulate_instance_locations' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
  267 | static auto repopulate_instance_locations(
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/jsonschema.cc:16:13: error: function 'id_keyword_guess' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   16 | static auto id_keyword_guess(const sourcemeta::core::JSON &schema)
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/jsonschema.cc:31:13: error: function 'id_keyword' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   31 | static auto id_keyword(const std::string &base_dialect) -> std::string {
      |             ^

/Users/jviotti/Projects/core/src/core/jsonschema/resolver.cc:92:13: error: function 'to_lowercase' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   92 | static auto to_lowercase(const std::string_view input) -> std::string {
      |             ^

/Users/jviotti/Projects/core/src/core/uri/uri.cc:16:13: error: function 'uri_normalize' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   16 | static auto uri_normalize(UriUriA *uri) -> void {
      |             ^

/Users/jviotti/Projects/core/src/core/uri/uri.cc:22:13: error: function 'uri_to_string' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   22 | static auto uri_to_string(const UriUriA *const uri) -> std::string {
      |             ^

/Users/jviotti/Projects/core/src/core/uri/uri.cc:39:13: error: function 'uri_text_range' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   39 | static auto uri_text_range(const UriTextRangeA *const range)
      |             ^

/Users/jviotti/Projects/core/src/core/uri/uri.cc:50:13: error: function 'uri_parse' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   50 | static auto uri_parse(const std::string &data, UriUriA *uri) -> void {
      |             ^

/Users/jviotti/Projects/core/src/core/uri/uri.cc:70:13: error: function 'canonicalize_path' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   70 | static auto canonicalize_path(const std::string &path)
      |             ^

/Users/jviotti/Projects/core/src/core/yaml/yaml.cc:12:13: error: function 'yaml_node_to_json' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   12 | static auto yaml_node_to_json(yaml_node_t *const node,
      |             ^

/Users/jviotti/Projects/core/src/core/yaml/yaml.cc:84:13: error: function 'internal_parse_json' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
   84 | static auto internal_parse_json(yaml_parser_t *parser)
      |             ^

```

### PR DESCRIPTION
**Pull request by bavulapati**
fixes #1678

### CODE REVIEW

**Comment by bavulapati** [comment]
> Looks generally good, but keep in mind that when you use the anonymous namespace, you should also remove the `static` qualifiers for each of the helper functions

Thanks for catching it. It's either static or anonymous namespace.

File: src/core/jsonschema/frame.cc
Comment (jviotti) [inline src/core/jsonschema/frame.cc:1]: In this file, we can add a single `namespace {` for every private entry. I think we have multiple here

File: src/core/jsonschema/frame.cc [hunk 1]
```diff
@@ -118,6 +120,8 @@ static auto find_nearest_bases(
   return {{}, sourcemeta::core::empty_pointer};
 }
 
+} // namespace
+
 static auto find_every_base(
```
Comment (jviotti) [inline src/core/jsonschema/frame.cc:125]: This one is not getting added to the anonymous namespace?

**Comment by jviotti** [comment]
From what I can see, this specific commit is missing the sign-off

Screenshot 2025-06-19 at 13 56 31
